# Generated by Django 2.2.15 on 2022-08-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
