# Generated by Django 2.2.15 on 2022-08-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_order',
            field=models.IntegerField(default=1),
        ),
    ]
